[is]
  title = "Vefsvæði BioPol"
  languageName = "Íslenska"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/is"
  
[en]
  title = "BioPol"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"

